Search.appendIndex(
    [
                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayDataRecord",
            "name": "ArrayDataRecord",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayDataRecord.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayDataRecord\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayDataRecord.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayDataRecord\u003A\u003AgetDataValue\u0028\u0029",
            "name": "getDataValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayDataRecord.html#method_getDataValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayDataRecord\u003A\u003AallData\u0028\u0029",
            "name": "allData",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayDataRecord.html#method_allData"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayDataRecord\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayDataRecord.html#property_data"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayRecord",
            "name": "ArrayRecord",
            "summary": "A\u0020simple\u0020array\u0020wrapper\u0020that\u0020implements\u0020\u0060RecordInterface\u0060",
            "url": "classes/Collecthor-SurveyjsParser-ArrayRecord.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayRecord\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayRecord.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayRecord\u003A\u003AgetRecordId\u0028\u0029",
            "name": "getRecordId",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayRecord.html#method_getRecordId"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayRecord\u003A\u003AgetStarted\u0028\u0029",
            "name": "getStarted",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayRecord.html#method_getStarted"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayRecord\u003A\u003AgetLastUpdate\u0028\u0029",
            "name": "getLastUpdate",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayRecord.html#method_getLastUpdate"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayRecord\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayRecord.html#property_id"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayRecord\u003A\u003A\u0024started",
            "name": "started",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayRecord.html#property_started"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ArrayRecord\u003A\u003A\u0024lastUpdate",
            "name": "lastUpdate",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ArrayRecord.html#property_lastUpdate"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ElementParserInterface",
            "name": "ElementParserInterface",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ElementParserInterface.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ElementParserInterface\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ElementParserInterface.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Helpers\\OptionGenerator",
            "name": "OptionGenerator",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Helpers-OptionGenerator.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Helpers\\OptionGenerator\u003A\u003AgenerateOptionsFromUnitEnum\u0028\u0029",
            "name": "generateOptionsFromUnitEnum",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Helpers-OptionGenerator.html#method_generateOptionsFromUnitEnum"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Helpers\\OptionGenerator\u003A\u003AgenerateOptionsFromBackedEnum\u0028\u0029",
            "name": "generateOptionsFromBackedEnum",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Helpers-OptionGenerator.html#method_generateOptionsFromBackedEnum"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\JavascriptVariableSet",
            "name": "JavascriptVariableSet",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-JavascriptVariableSet.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\JavascriptVariableSet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-JavascriptVariableSet.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\JavascriptVariableSet\u003A\u003AgetVariableNames\u0028\u0029",
            "name": "getVariableNames",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-JavascriptVariableSet.html#method_getVariableNames"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\JavascriptVariableSet\u003A\u003AgetVariable\u0028\u0029",
            "name": "getVariable",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-JavascriptVariableSet.html#method_getVariable"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\JavascriptVariableSet\u003A\u003AgetVariables\u0028\u0029",
            "name": "getVariables",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-JavascriptVariableSet.html#method_getVariables"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\JavascriptVariableSet\u003A\u003A\u0024variables",
            "name": "variables",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-JavascriptVariableSet.html#property_variables"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\LocalizerInterface",
            "name": "LocalizerInterface",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-LocalizerInterface.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\LocalizerInterface\u003A\u003AgetAllTranslationsForString\u0028\u0029",
            "name": "getAllTranslationsForString",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-LocalizerInterface.html#method_getAllTranslationsForString"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers",
            "name": "ParserHelpers",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AparseCommentField\u0028\u0029",
            "name": "parseCommentField",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_parseCommentField"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AextractTitles\u0028\u0029",
            "name": "extractTitles",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_extractTitles"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AextractValueName\u0028\u0029",
            "name": "extractValueName",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_extractValueName"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AextractLocalizedTexts\u0028\u0029",
            "name": "extractLocalizedTexts",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_extractLocalizedTexts"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AextractArray\u0028\u0029",
            "name": "extractArray",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_extractArray"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AextractName\u0028\u0029",
            "name": "extractName",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_extractName"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AextractOptionalBoolean\u0028\u0029",
            "name": "extractOptionalBoolean",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_extractOptionalBoolean"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AextractChoices\u0028\u0029",
            "name": "extractChoices",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_extractChoices"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserHelpers\u003A\u003AarrayFormat\u0028\u0029",
            "name": "arrayFormat",
            "summary": "Concat\u0020a\u0020combination\u0020of\u0020localized\u0020strings\u0020and\u0020normal\u0020ones",
            "url": "classes/Collecthor-SurveyjsParser-ParserHelpers.html#method_arrayFormat"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserLocalizer",
            "name": "ParserLocalizer",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserLocalizer.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserLocalizer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020ParserLocalizer",
            "url": "classes/Collecthor-SurveyjsParser-ParserLocalizer.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserLocalizer\u003A\u003AgetAllTranslationsForString\u0028\u0029",
            "name": "getAllTranslationsForString",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserLocalizer.html#method_getAllTranslationsForString"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserLocalizer\u003A\u003A\u0024rowLabels",
            "name": "rowLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserLocalizer.html#property_rowLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserLocalizer\u003A\u003A\u0024positiveLabels",
            "name": "positiveLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserLocalizer.html#property_positiveLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserLocalizer\u003A\u003A\u0024textLabels",
            "name": "textLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserLocalizer.html#property_textLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserLocalizer\u003A\u003A\u0024trueLabels",
            "name": "trueLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserLocalizer.html#property_trueLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\ParserLocalizer\u003A\u003A\u0024falseLabels",
            "name": "falseLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-ParserLocalizer.html#property_falseLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\BooleanParser",
            "name": "BooleanParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-BooleanParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\BooleanParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-BooleanParser.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\BooleanParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-BooleanParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\BooleanParser\u003A\u003A\u0024trueLabels",
            "name": "trueLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-BooleanParser.html#property_trueLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\BooleanParser\u003A\u003A\u0024falseLabels",
            "name": "falseLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-BooleanParser.html#property_falseLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\CallbackElementParser",
            "name": "CallbackElementParser",
            "summary": "An\u0020element\u0020parser\u0020that\u0020uses\u0020a\u0020closure\u0020to\u0020parse\u0020any\u0020given\u0020question\u0020configuration.",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-CallbackElementParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\CallbackElementParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-CallbackElementParser.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\CallbackElementParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-CallbackElementParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\CallbackElementParser\u003A\u003A\u0024callback",
            "name": "callback",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-CallbackElementParser.html#property_callback"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\CommentParser",
            "name": "CommentParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-CommentParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\CommentParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-CommentParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\DummyParser",
            "name": "DummyParser",
            "summary": "A\u0020parser\u0020that\u0020always\u0020resolves\u0020to\u0020an\u0020empty\u0020list\u0020of\u0020variables",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-DummyParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\DummyParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-DummyParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\ImagePickerParser",
            "name": "ImagePickerParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-ImagePickerParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\ImagePickerParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-ImagePickerParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\MultipleChoiceQuestionParser",
            "name": "MultipleChoiceQuestionParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-MultipleChoiceQuestionParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\MultipleChoiceQuestionParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-MultipleChoiceQuestionParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\MultipleTextParser",
            "name": "MultipleTextParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-MultipleTextParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\MultipleTextParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-MultipleTextParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\PanelParser",
            "name": "PanelParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-PanelParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\PanelParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-PanelParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\RankingParser",
            "name": "RankingParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-RankingParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\RankingParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-RankingParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\RatingParser",
            "name": "RatingParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-RatingParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\RatingParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-RatingParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\SingleChoiceQuestionParser",
            "name": "SingleChoiceQuestionParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-SingleChoiceQuestionParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\SingleChoiceQuestionParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-SingleChoiceQuestionParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\TextQuestionParser",
            "name": "TextQuestionParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-TextQuestionParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers\\TextQuestionParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Parsers-TextQuestionParser.html#method_parse"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyConfiguration",
            "name": "SurveyConfiguration",
            "summary": "Survey\u0020wide\u0020configuration\u0020settings\u0020that\u0020affect\u0020parsing\u0020of\u0020individual\u0020questions",
            "url": "classes/Collecthor-SurveyjsParser-SurveyConfiguration.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyConfiguration\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyConfiguration.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyConfiguration\u003A\u003A\u0024commentPostfix",
            "name": "commentPostfix",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyConfiguration.html#property_commentPostfix"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyConfiguration\u003A\u003A\u0024locales",
            "name": "locales",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyConfiguration.html#property_locales"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser",
            "name": "SurveyParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AsetParser\u0028\u0029",
            "name": "setParser",
            "summary": "Sets\u0020the\u0020parser\u0020for\u0020a\u0020specific\u0020question,\u0020removes\u0020all\u0020other\u0020registered\u0020parser\u0020for\u0020this\u0020question\u0020parser.",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_setParser"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AaddParser\u0028\u0029",
            "name": "addParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_addParser"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AsetDefaultParser\u0028\u0029",
            "name": "setDefaultParser",
            "summary": "Sets\u0020the\u0020default\u0020parser",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_setDefaultParser"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AgetParsers\u0028\u0029",
            "name": "getParsers",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_getParsers"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AparseElement\u0028\u0029",
            "name": "parseElement",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_parseElement"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AparsePage\u0028\u0029",
            "name": "parsePage",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_parsePage"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AparseSurveyStructure\u0028\u0029",
            "name": "parseSurveyStructure",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_parseSurveyStructure"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AparseJson\u0028\u0029",
            "name": "parseJson",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_parseJson"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003AextractString\u0028\u0029",
            "name": "extractString",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#method_extractString"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003A\u0024parsers",
            "name": "parsers",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#property_parsers"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003A\u0024defaultParser",
            "name": "defaultParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#property_defaultParser"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParser\u003A\u003A\u0024recursiveParser",
            "name": "recursiveParser",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParser.html#property_recursiveParser"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParserInterface",
            "name": "SurveyParserInterface",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParserInterface.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParserInterface\u003A\u003AsetParser\u0028\u0029",
            "name": "setParser",
            "summary": "Sets\u0020a\u0020parser\u0020for\u0020a\u0020question\u0020type.\u0020Will\u0020override\u0020the\u0020previously\u0020configured\u0020or\u0020default\u0020parser.",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParserInterface.html#method_setParser"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParserInterface\u003A\u003AsetDefaultParser\u0028\u0029",
            "name": "setDefaultParser",
            "summary": "Sets\u0020the\u0020default\u0020parser",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParserInterface.html#method_setDefaultParser"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParserInterface\u003A\u003AparseSurveyStructure\u0028\u0029",
            "name": "parseSurveyStructure",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParserInterface.html#method_parseSurveyStructure"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\SurveyParserInterface\u003A\u003AparseJson\u0028\u0029",
            "name": "parseJson",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-SurveyParserInterface.html#method_parseJson"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetDisplayValue",
            "name": "GetDisplayValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetDisplayValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetDisplayValue\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetDisplayValue.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetDisplayValue\u003A\u003AgetDisplayValues\u0028\u0029",
            "name": "getDisplayValues",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetDisplayValue.html#method_getDisplayValues"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetName",
            "name": "GetName",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetName.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetName\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetName.html#method_getName"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetName\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetName.html#property_name"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetRawConfiguration",
            "name": "GetRawConfiguration",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetRawConfiguration.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetRawConfiguration\u003A\u003AgetRawConfigurationValue\u0028\u0029",
            "name": "getRawConfigurationValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetRawConfiguration.html#method_getRawConfigurationValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetRawConfiguration\u003A\u003A\u0024rawConfiguration",
            "name": "rawConfiguration",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetRawConfiguration.html#property_rawConfiguration"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetTitle",
            "name": "GetTitle",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetTitle.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetTitle\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetTitle.html#method_getTitle"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits\\GetTitle\u003A\u003A\u0024titles",
            "name": "titles",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Traits-GetTitle.html#property_titles"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValue",
            "name": "BooleanValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValue.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValue\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValue.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValue\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValue.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValueOption",
            "name": "BooleanValueOption",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValueOption.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValueOption\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValueOption.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValueOption\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValueOption.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValueOption\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValueOption.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\BooleanValueOption\u003A\u003A\u0024displayValues",
            "name": "displayValues",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-BooleanValueOption.html#property_displayValues"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\FloatValue",
            "name": "FloatValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-FloatValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\FloatValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-FloatValue.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\FloatValue\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-FloatValue.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\FloatValue\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-FloatValue.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValue",
            "name": "IntegerValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValue.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValue\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValue.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValue\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValue.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValueOption",
            "name": "IntegerValueOption",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValueOption.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValueOption\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValueOption.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValueOption\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValueOption.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValueOption\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValueOption.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\IntegerValueOption\u003A\u003A\u0024displayValues",
            "name": "displayValues",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-IntegerValueOption.html#property_displayValues"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\InvalidValue",
            "name": "InvalidValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-InvalidValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\InvalidValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-InvalidValue.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\InvalidValue\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-InvalidValue.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\InvalidValue\u003A\u003AisSystemMissing\u0028\u0029",
            "name": "isSystemMissing",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-InvalidValue.html#method_isSystemMissing"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\InvalidValue\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-InvalidValue.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingBooleanValue",
            "name": "MissingBooleanValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingBooleanValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingBooleanValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingBooleanValue.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingBooleanValue\u003A\u003A\u0024isSystemMissing",
            "name": "isSystemMissing",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingBooleanValue.html#property_isSystemMissing"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingBooleanValue\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingBooleanValue.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingBooleanValue\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingBooleanValue.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingIntegerValue",
            "name": "MissingIntegerValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingIntegerValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingIntegerValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingIntegerValue.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingIntegerValue\u003A\u003A\u0024isSystemMissing",
            "name": "isSystemMissing",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingIntegerValue.html#property_isSystemMissing"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingIntegerValue\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingIntegerValue.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingIntegerValue\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingIntegerValue.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingStringValue",
            "name": "MissingStringValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingStringValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingStringValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingStringValue.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingStringValue\u003A\u003A\u0024isSystemMissing",
            "name": "isSystemMissing",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingStringValue.html#property_isSystemMissing"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingStringValue\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingStringValue.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\MissingStringValue\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-MissingStringValue.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValue",
            "name": "StringValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValue.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValue\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValue.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValue\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValue.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValue\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValue.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValueOption",
            "name": "StringValueOption",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValueOption.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValueOption\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValueOption.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValueOption\u003A\u003AgetRawValue\u0028\u0029",
            "name": "getRawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValueOption.html#method_getRawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValueOption\u003A\u003A\u0024rawValue",
            "name": "rawValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValueOption.html#property_rawValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\StringValueOption\u003A\u003A\u0024displayValues",
            "name": "displayValues",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-StringValueOption.html#property_displayValues"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\ValueSet",
            "name": "ValueSet",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-ValueSet.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\ValueSet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-ValueSet.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\ValueSet\u003A\u003AgetValues\u0028\u0029",
            "name": "getValues",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-ValueSet.html#method_getValues"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values\\ValueSet\u003A\u003A\u0024values",
            "name": "values",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Values-ValueSet.html#property_values"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable",
            "name": "BooleanVariable",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003AgetValueOptions\u0028\u0029",
            "name": "getValueOptions",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#method_getValueOptions"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#method_getValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003AgetMeasure\u0028\u0029",
            "name": "getMeasure",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#method_getMeasure"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#property_name"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003A\u0024titles",
            "name": "titles",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#property_titles"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003A\u0024trueLabels",
            "name": "trueLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#property_trueLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003A\u0024falseLabels",
            "name": "falseLabels",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#property_falseLabels"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003A\u0024dataPath",
            "name": "dataPath",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#property_dataPath"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\BooleanVariable\u003A\u003A\u0024rawConfiguration",
            "name": "rawConfiguration",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-BooleanVariable.html#property_rawConfiguration"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\MultipleChoiceVariable",
            "name": "MultipleChoiceVariable",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-MultipleChoiceVariable.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\MultipleChoiceVariable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-MultipleChoiceVariable.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\MultipleChoiceVariable\u003A\u003AgetValueOptions\u0028\u0029",
            "name": "getValueOptions",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-MultipleChoiceVariable.html#method_getValueOptions"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\MultipleChoiceVariable\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-MultipleChoiceVariable.html#method_getValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\MultipleChoiceVariable\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-MultipleChoiceVariable.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\MultipleChoiceVariable\u003A\u003AgetMeasure\u0028\u0029",
            "name": "getMeasure",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-MultipleChoiceVariable.html#method_getMeasure"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\MultipleChoiceVariable\u003A\u003A\u0024valueMap",
            "name": "valueMap",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-MultipleChoiceVariable.html#property_valueMap"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\MultipleChoiceVariable\u003A\u003A\u0024dataPath",
            "name": "dataPath",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-MultipleChoiceVariable.html#property_dataPath"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\NumericVariable",
            "name": "NumericVariable",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-NumericVariable.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\NumericVariable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-NumericVariable.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\NumericVariable\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-NumericVariable.html#method_getValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\NumericVariable\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-NumericVariable.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\NumericVariable\u003A\u003AgetMeasure\u0028\u0029",
            "name": "getMeasure",
            "summary": "Numerical\u0020variables\u0020are\u0020always\u0020ordered,\u0020they\u0020might\u0020even\u0020be\u0020scalar,\u0020but\u0020that\u0020depends\u0020on\u0020context.",
            "url": "classes/Collecthor-SurveyjsParser-Variables-NumericVariable.html#method_getMeasure"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\NumericVariable\u003A\u003AgetJavascriptRepresentation\u0028\u0029",
            "name": "getJavascriptRepresentation",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-NumericVariable.html#method_getJavascriptRepresentation"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\NumericVariable\u003A\u003A\u0024dataPath",
            "name": "dataPath",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-NumericVariable.html#property_dataPath"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\OpenTextVariable",
            "name": "OpenTextVariable",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-OpenTextVariable.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\OpenTextVariable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-OpenTextVariable.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\OpenTextVariable\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-OpenTextVariable.html#method_getValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\OpenTextVariable\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-OpenTextVariable.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\OpenTextVariable\u003A\u003AgetMeasure\u0028\u0029",
            "name": "getMeasure",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-OpenTextVariable.html#method_getMeasure"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\OpenTextVariable\u003A\u003AgetJavascriptRepresentation\u0028\u0029",
            "name": "getJavascriptRepresentation",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-OpenTextVariable.html#method_getJavascriptRepresentation"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\OpenTextVariable\u003A\u003A\u0024dataPath",
            "name": "dataPath",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-OpenTextVariable.html#property_dataPath"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable",
            "name": "SingleChoiceVariable",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable\u003A\u003AgetValueOptions\u0028\u0029",
            "name": "getValueOptions",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html#method_getValueOptions"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html#method_getValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable\u003A\u003AgetDisplayValue\u0028\u0029",
            "name": "getDisplayValue",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html#method_getDisplayValue"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable\u003A\u003AgetMeasure\u0028\u0029",
            "name": "getMeasure",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html#method_getMeasure"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable\u003A\u003AgetJavascriptRepresentation\u0028\u0029",
            "name": "getJavascriptRepresentation",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html#method_getJavascriptRepresentation"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable\u003A\u003A\u0024valueMap",
            "name": "valueMap",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html#property_valueMap"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables\\SingleChoiceVariable\u003A\u003A\u0024dataPath",
            "name": "dataPath",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-Variables-SingleChoiceVariable.html#property_dataPath"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\VariableSet",
            "name": "VariableSet",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-VariableSet.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\VariableSet\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-VariableSet.html#method___construct"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\VariableSet\u003A\u003AgetVariableNames\u0028\u0029",
            "name": "getVariableNames",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-VariableSet.html#method_getVariableNames"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\VariableSet\u003A\u003AgetVariable\u0028\u0029",
            "name": "getVariable",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-VariableSet.html#method_getVariable"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\VariableSet\u003A\u003AgetVariables\u0028\u0029",
            "name": "getVariables",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-VariableSet.html#method_getVariables"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\VariableSet\u003A\u003A\u0024variables",
            "name": "variables",
            "summary": "",
            "url": "classes/Collecthor-SurveyjsParser-VariableSet.html#property_variables"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser",
            "name": "SurveyjsParser",
            "summary": "",
            "url": "namespaces/collecthor-surveyjsparser.html"
        },                {
            "fqsen": "\\Collecthor",
            "name": "Collecthor",
            "summary": "",
            "url": "namespaces/collecthor.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/collecthor-surveyjsparser-helpers.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Parsers",
            "name": "Parsers",
            "summary": "",
            "url": "namespaces/collecthor-surveyjsparser-parsers.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/collecthor-surveyjsparser-traits.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Values",
            "name": "Values",
            "summary": "",
            "url": "namespaces/collecthor-surveyjsparser-values.html"
        },                {
            "fqsen": "\\Collecthor\\SurveyjsParser\\Variables",
            "name": "Variables",
            "summary": "",
            "url": "namespaces/collecthor-surveyjsparser-variables.html"
        }            ]
);
